.TH EDIT 1 edit\-VERSION
.SH NAME
edit \- A suckless, simple, featured text editor.
.SH SYNOPSIS
.B edit 
.IB file
.SH DESCRIPTION
edit aims to provide a simple and powerful editing model, in a suckless-style
codebase.
.SH USAGE
For learning how to use edit, please do the tutorial distributed with the
code:
.BR make\ tutor
.P
A
.IR cheatsheet.md
is also provided for quick reference.
.SH CUSTOMIZATION
edit is customized by creating a custom config.h and (re)compiling the
source code. This keeps it fast, secure and simple.
